### ISSUE TITLE
restart dockers

### ISSUE THREAD

**Issue by arnounesco** [iodepo/oih-ui-docker#10]
seems like the dockers do not start automatically, when updating and upgrading the servers they are often restarted and the dockers for the search do not come up

**Comment by EricSoroos** [comment]
On our ubuntu servers, we have a `docker-compose.service` at   `/etc/systemd/system/docker-compose.service` with the contents: 

```
##
##  Installation --
##
## copy this file to /etc/systemd/system/docker-compose.service
## sudo systemctl enable docker-compose.service
##
## this should work on ubuntu 16.04

[Unit]
Description=Docker-Compose Runtime
After=docker.service
Wants=docker.service
Requires=docker.service

[Service]
#Restart=always

##
## Note -- set the path to the environment file below,
## as well as the path to the docker-compose file.
##
EnvironmentFile=/[path-to-docker-compose]/.env
ExecStart=/usr/local/bin/docker-compose -f /[path-to-docker-compose]/docker-compose.yml up
ExecStop=/usr/local/bin/docker-compose -f /[path-to-docker-compose]/docker-compose.yml down

[Install]
WantedBy=default.target
```

Once it's installed, `sudo systemctl enable docker-compose.service` enables it, and then it will come up on reboot.

**Comment by arnounesco** [comment]
https://github.com/iodepo/oih-ui-docker/commit/70db6a393c6151331357ee2fefbed2c1b12f051c
